### PR TITLE
Switch from pipenv to nox

### PR DESCRIPTION
**Pull request by messense**
pipenv is way too slow.

nox: https://nox.thea.codes/

### CODE REVIEW

**Comment by ChillFish8** [comment]
Any particular reason for using nox over say Poetry?

**Comment by messense** [comment]
Well, this project uses maturin so it does not really need another PEP 517 build backend and [Poetry doesn't support PEP 621](https://github.com/python-poetry/poetry/issues/3332).

**Comment by ChillFish8** [comment]
> Well, this project uses Maturin so it does not really need another PEP 517 build backend and Poetry doesn't support PEP 621.
Fair enough

**Review by ChillFish8 — APPROVED** [review]
Looks fine to me, although If we ever add standard dependencies (although very unlikely) we'll want a lock file present (not sure if nox provides that for non-dev deps)

**Pull request merged**
