### PR TITLE
expose regex query

### PR DESCRIPTION
**Pull request by alex-au-922**
Exposed the regex query function based on the rust version's crate documentation.

Expected usage:

```python
@staticmethod
def regex_query(schema: Schema, field_name: str, regex_pattern: str) -> Query:
    ...

query = Query.regex_query(index.schema, "body", "fish")
```

Raises error if the field name doesn't found, or the regex pattern is not valid.

Currently this query must be created outside from the query parser

### CODE REVIEW

**Comment by cjrh** [comment]
@alex-au-922 If you can fix up the conflicts (from merging your other `BooleanQuery` PR) I'll merge this one as well.

**Comment by alex-au-922** [comment]
Thanks, will fix it soon

**Comment by cjrh** [comment]
All good, I'm not rushing you 😄 . Whenever you have time.

**Review by cjrh — APPROVED** [review]

**Comment by cjrh** [comment]
Oops sorry for the conflicts again.  Should I have merged this one before boost query?

Anyway, we're getting there.  After the conflicts are fixed here we can merge this too.

**Comment by alex-au-922** [comment]
Let me update both the expose regex query and expose boost query (later after you have merged).

**Pull request merged**
